** *italicised text*استدعاء المكتبات**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**تحميل الملفات 14 جدول مرة واحدة **

In [ ]:

import os

# 1. تحديد مسار المجلد (درايف جوجل )
folder_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/'

# 2. إنشاء {} قاموس ليحتوي على كل البيانات
all_data = {}

# 3. لقراءة كل ملفات CSV في المجلد
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        # استخراج اسم الجدول (مثلاً 'trips' بدلاً من 'trips.csv')
        table_name = file_name.replace('.csv', '')# هيحط مسافة فاضية مكانها

        # قراءة الملف وتخزينه
        all_data[table_name] = pd.read_csv(os.path.join(folder_path, file_name))

        print(f"✅ تم تحميل الجدول: {table_name}")

✅ تم تحميل الجدول: delivery_events
✅ تم تحميل الجدول: customers
✅ تم تحميل الجدول: safety_incidents
✅ تم تحميل الجدول: drivers
✅ تم تحميل الجدول: loads
✅ تم تحميل الجدول: fuel_purchases
✅ تم تحميل الجدول: driver_monthly_metrics
✅ تم تحميل الجدول: routes
✅ تم تحميل الجدول: trips
✅ تم تحميل الجدول: facilities
✅ تم تحميل الجدول: maintenance_records
✅ تم تحميل الجدول: trailers
✅ تم تحميل الجدول: trucks
✅ تم تحميل الجدول: truck_utilization_metrics

**الاستعلام عن البيانات **

 استكشاف البيانات (Data Exploration)

In [ ]:
# نظرة سريعة على أسماء الأعمدة وعدد الصفوف في كل جدول
for name, df in all_data.items():
    print(f"📊 الجدول: {name} | عدد الصفوف: {df.shape[0]} | عدد الأعمدة: {df.shape[1]}")

📊 الجدول: delivery_events | عدد الصفوف: 170820 | عدد الأعمدة: 11
📊 الجدول: customers | عدد الصفوف: 200 | عدد الأعمدة: 8
📊 الجدول: safety_incidents | عدد الصفوف: 170 | عدد الأعمدة: 15
📊 الجدول: drivers | عدد الصفوف: 150 | عدد الأعمدة: 12
📊 الجدول: loads | عدد الصفوف: 85410 | عدد الأعمدة: 12
📊 الجدول: fuel_purchases | عدد الصفوف: 196442 | عدد الأعمدة: 11
📊 الجدول: driver_monthly_metrics | عدد الصفوف: 4464 | عدد الأعمدة: 9
📊 الجدول: routes | عدد الصفوف: 58 | عدد الأعمدة: 9
📊 الجدول: trips | عدد الصفوف: 85410 | عدد الأعمدة: 12
📊 الجدول: facilities | عدد الصفوف: 50 | عدد الأعمدة: 9
📊 الجدول: maintenance_records | عدد الصفوف: 2920 | عدد الأعمدة: 12
📊 الجدول: trailers | عدد الصفوف: 180 | عدد الأعمدة: 9
📊 الجدول: trucks | عدد الصفوف: 120 | عدد الأعمدة: 11
📊 الجدول: truck_utilization_metrics | عدد الصفوف: 3312 | عدد الأعمدة: 10

العمل على الجداول الاساسية

1.   trips

In [ ]:
# 1. عرض معلومات الجدول (أنواع البيانات والقيم المفقودة)
print("📊 معلومات جدول الرحلات (Trips Info):")
print(all_data['trips'].info())

print("\n" + "="*30 + "\n")

# 2. عرض أول 5 صفوف لنلقي نظرة بالعين على البيانات
print(" أول 5 رحلات:")
display(all_data['trips'].head())

📊 معلومات جدول الرحلات (Trips Info):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                85410 non-null  object
 1   load_id                85410 non-null  object
 2   driver_id              83696 non-null  object
 3   truck_id               83738 non-null  object
 4   trailer_id             83730 non-null  object
 5   dispatch_date          85410 non-null  object
 6   actual_distance_miles  85410 non-null  int64
 7   actual_duration_hours  85410 non-null  float64
 8   fuel_gallons_used      85410 non-null  float64
 9   average_mpg            85410 non-null  float64
 10  idle_time_hours        85410 non-null  float64
 11  trip_status            85410 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 7.8+ MB
None

==============================

 أول 5 رحلات:

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed
3,TRIP00000004,LOAD00000004,DRV00083,TRK00105,TRL00018,2022-01-01,717,11.1,110.3,6.50,9.6,Completed
4,TRIP00000005,LOAD00000005,DRV00044,TRK00076,TRL00054,2022-01-01,2243,35.0,328.9,6.82,11.6,Completed

In [ ]:
df.isnull().sum() # مشتغلش عشان الجدول داخل all data

truck_id              0
month                 0
trips_completed       0
total_miles           0
total_revenue         0
average_mpg           0
maintenance_events    0
maintenance_cost      0
downtime_hours        0
utilization_rate      0
dtype: int64

Data Profiling

In [ ]:
# --- عرض المشاكل قبل التنظيف (Diagnostic Phase) ---

print("🔍 فحص القيم المفقودة في جدول الرحلات (Trips):")
# الوصول للجدول من داخل القاموس مباشرة
trips_nulls = all_data['trips'].isnull().sum()
print(trips_nulls)

print("\n" + "="*40 + "\n")

# عرض الصفوف التي تحتوي على قيم مفقودة في السائق أو الشاحنة للتأكد بالعين
print(" عينة من الصفوف التي تفتقد لبيانات السائق أو الشاحنة:")
missing_data_samples = all_data['trips'][all_data['trips']['driver_id'].isnull() | all_data['trips']['truck_id'].isnull()]
display(missing_data_samples.head())

🔍 فحص القيم المفقودة في جدول الرحلات (Trips):
trip_id                     0
load_id                     0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
trip_status                 0
dtype: int64

========================================

 عينة من الصفوف التي تفتقد لبيانات السائق أو الشاحنة:

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
66,TRIP00000067,LOAD00000067,NaN,TRK00112,TRL00040,2022-01-01,2433,40.0,427.6,5.69,9.2,Completed
69,TRIP00000070,LOAD00000070,DRV00077,NaN,TRL00040,2022-01-01,711,14.2,105.5,6.74,9.7,Completed
73,TRIP00000074,LOAD00000074,DRV00051,NaN,TRL00141,2022-01-02,2937,51.6,428.8,6.85,9.7,Completed
87,TRIP00000088,LOAD00000088,DRV00078,NaN,TRL00072,2022-01-02,864,14.5,127.8,6.76,12.0,Completed
103,TRIP00000104,LOAD00000104,NaN,TRK00114,TRL00013,2022-01-02,1048,18.5,143.2,7.32,4.6,Completed

In [ ]:
# 1. حذف الصفوف اللي فيها قيم مفقودة في الأعمدة الأساسية (الهيكل)
all_data['trips'] = all_data['trips'].dropna(subset=['driver_id', 'truck_id', 'trailer_id'])

# 2. تحويل البيانات للأعمدة المتبقية السليمة
all_data['trips']['dispatch_date'] = pd.to_datetime(all_data['trips']['dispatch_date'])

print("✅ تم الحذف أولاً ثم تحويل أنواع البيانات.")

✅ تم الحذف أولاً ثم تحويل أنواع البيانات.

In [ ]:
# 1. عرض معلومات الجدول  بعد الحذف)
print("📊 معلومات جدول الرحلات (Trips Info):")
print(all_data['trips'].info())

print("\n" + "="*30 + "\n")

📊 معلومات جدول الرحلات (Trips Info):
<class 'pandas.core.frame.DataFrame'>
Index: 80458 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                80458 non-null  object
 1   load_id                80458 non-null  object
 2   driver_id              80458 non-null  object
 3   truck_id               80458 non-null  object
 4   trailer_id             80458 non-null  object
 5   dispatch_date          80458 non-null  datetime64[ns]
 6   actual_distance_miles  80458 non-null  int64
 7   actual_duration_hours  80458 non-null  float64
 8   fuel_gallons_used      80458 non-null  float64
 9   average_mpg            80458 non-null  float64
 10  idle_time_hours        80458 non-null  float64
 11  trip_status            80458 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 8.0+ MB
None

==============================

In [ ]:
print("🔍 فحص القيم المفقودة في جدول الرحلات (Trips):")
# الوصول للجدول من داخل القاموس مباشرة
trips_nulls = all_data['trips'].isnull().sum()
print(trips_nulls)

print("\n" + "="*40 + "\n")

🔍 فحص القيم المفقودة في جدول الرحلات (Trips):
trip_id                  0
load_id                  0
driver_id                0
truck_id                 0
trailer_id               0
dispatch_date            0
actual_distance_miles    0
actual_duration_hours    0
fuel_gallons_used        0
average_mpg              0
idle_time_hours          0
trip_status              0
dtype: int64

========================================

In [ ]:
# 2. تحويل عمود التاريخ لنوع datetime
all_data['trips']['dispatch_date'] = pd.to_datetime(all_data['trips']['dispatch_date'])

print("✅ تم الحذف (بما في ذلك المقطورات) ثم تحويل أنواع البيانات.")
print(f"إجمالي الرحلات السليمة المتبقية: {len(all_data['trips'])}")

print("\n" + "="*40 + "\n")

# --- المرحلة الثالثة: التأكد (Validation) ---
print(" فحص القيم المفقودة بعد التنظيف ):")
print(all_data['trips'][['driver_id', 'truck_id', 'trailer_id']].isnull().sum())

✅ تم الحذف (بما في ذلك المقطورات) ثم تحويل أنواع البيانات.
إجمالي الرحلات السليمة المتبقية: 80458

========================================

 فحص القيم المفقودة بعد التنظيف ):
driver_id     0
truck_id      0
trailer_id    0
dtype: int64

حساب نسبة البيانات المحذوفة

In [ ]:
# 1. حفظ عدد الصفوف قبل الحذف
initial_count = 85410  # الرقم الذي ظهر لنا في info() أول مرة

# 2. الحصول على عدد الصفوف بعد الحذف
current_count = len(all_data['trips'])

# 3. حساب عدد الصفوف المحذوفة
deleted_count = initial_count - current_count

# 4. حساب النسبة المئوية
deletion_percentage = (deleted_count / initial_count) * 100

print(f"📊 تقرير تنظيف البيانات (جدول Trips):")
print(f"   - إجمالي البيانات الأصلية: {initial_count}")
print(f"   - عدد الصفوف المحذوفة: {deleted_count}")
print(f"   - نسبة البيانات المحذوفة: {deletion_percentage:.2f}%")
print(f"   - البيانات المتبقية للتحليل: {current_count}")

📊 تقرير تنظيف البيانات (جدول Trips):
   - إجمالي البيانات الأصلية: 85410
   - عدد الصفوف المحذوفة: 4952
   - نسبة البيانات المحذوفة: 5.80%
   - البيانات المتبقية للتحليل: 80458

هنزامن الجداول باستخدام trip id and compare each colomn

In [ ]:
# 1. تجهيز القوائم للربط (Sets are faster for searching)
valid_trips = set(all_data['trips']['trip_id'])
valid_loads = set(all_data['trips']['load_id'])

print(" بدء عملية المزامنة لضمان ترابط البيانات (Referential Integrity):")
print("-" * 50)#مسافة بخط

# 2. كود للمزامنة التلقائية لأي جدول مرتبط بالرحلة مباشرة
for name, df in all_data.items():
    # تخطي جدول الرحلات نفسه لأنه المرجع
    if name == 'trips': continue

    # المزامنة عبر trip_id
    if 'trip_id' in df.columns:
        initial_count = len(df)
        all_data[name] = df[df['trip_id'].isin(valid_trips)]
        print(f"✅ تم مزامنة {name:20} | حذف: {initial_count - len(all_data[name]):<5} صفوف")

# 3. مزامنة جدول الأحمال (حالة خاصة لأنه يرتبط عبر load_id)
if 'loads' in all_data:
    initial_count = len(all_data['loads'])
    all_data['loads'] = all_data['loads'][all_data['loads']['load_id'].isin(valid_loads)]
    print(f"✅ تم مزامنة {'loads':20} | حذف: {initial_count - len(all_data['loads']):<5} صفوف (عبر load_id)")

print("-" * 50)
print("🎯 انتهت المزامنة.. الآن كل الجداول مرتبطة برحلات حقيقية وسليمة.")

 بدء عملية المزامنة لضمان ترابط البيانات (Referential Integrity):
--------------------------------------------------
✅ تم مزامنة delivery_events      | حذف: 9904  صفوف
✅ تم مزامنة safety_incidents     | حذف: 5     صفوف
✅ تم مزامنة fuel_purchases       | حذف: 11391 صفوف
✅ تم مزامنة loads                | حذف: 4952  صفوف (عبر load_id)
--------------------------------------------------
🎯 انتهت المزامنة.. الآن كل الجداول مرتبطة برحلات حقيقية وسليمة.

In [ ]:
# 1. تجهيز القوائم للربط (Sets) لسرعة البحث
valid_trips = set(all_data['trips']['trip_id'])
valid_loads = set(all_data['trips']['load_id'])

print(" تقرير مزامنة البيانات (Data Synchronization Report):")
print("-" * 65)
print(f"{'الجدول':<20} | {'قبل':<8} | {'بعد':<8} | {'المحذوف':<8}")
print("-" * 65)

# 2. حلقة المزامنة التلقائية للجداول المرتبطة بـ trip_id
for name, df in all_data.items():
    if name == 'trips': continue

    if 'trip_id' in df.columns:
        before_count = len(df)
        all_data[name] = df[df['trip_id'].isin(valid_trips)]
        after_count = len(all_data[name])
        deleted = before_count - after_count

        print(f"{name:<20} | {before_count:<8} | {after_count:<8} | {deleted:<8}")

# 3. مزامنة جدول الأحمال (Loads) حالة خاصة عبر load_id
if 'loads' in all_data:
    before_count = len(all_data['loads'])
    all_data['loads'] = all_data['loads'][all_data['loads']['load_id'].isin(valid_loads)]
    after_count = len(all_data['loads'])
    deleted = before_count - after_count

    print(f"{'loads (via load_id)':<20} | {before_count:<8} | {after_count:<8} | {deleted:<8}")

print("-" * 65)
print(" تم تنقية جميع الجداول من البيانات غير المرتبطة برحلات سليمة.")

 تقرير مزامنة البيانات (Data Synchronization Report):
-----------------------------------------------------------------
الجدول               | قبل      | بعد      | المحذوف
-----------------------------------------------------------------
delivery_events      | 160916   | 160916   | 0
safety_incidents     | 165      | 165      | 0
fuel_purchases       | 185051   | 185051   | 0
loads (via load_id)  | 80458    | 80458    | 0
-----------------------------------------------------------------
 تم تنقية جميع الجداول من البيانات غير المرتبطة برحلات سليمة.

In [ ]:
# 1. أولاً: نحدد المراجع السليمة (الرحلات والأحمال التي لم تُحذف)
valid_trips = set(all_data['trips']['trip_id'])
valid_loads = set(all_data['trips']['load_id'])

print(" إعادة مزامنة البيانات (Data Synchronization Report):")
print("-" * 70)
# رأس الجدول للتنسيق
print(f"{'الجدول':<25} | {'قبل الحذف':<10} | {'بعد الحذف':<10} | {'المحذوف':<10}")
print("-" * 70)

# 2. حلقة تمر على كل الجداول لمزامنة أي جدول يحتوي على trip_id
for name, df in all_data.items():
    if name == 'trips': continue  # نتخطى جدول الرحلات لأنه هو المرجع الأساسي

    if 'trip_id' in df.columns:
        before_count = len(df)
        # الاحتفاظ فقط بالصفوف المرتبطة برحلات سليمة
        all_data[name] = df[df['trip_id'].isin(valid_trips)].copy()
        after_count = len(all_data[name])
        deleted = before_count - after_count

        print(f"{name:<25} | {before_count:<10} | {after_count:<10} | {deleted:<10}")

# 3. مزامنة جدول الأحمال (حالة خاصة لأنه يرتبط بـ load_id)
if 'loads' in all_data:
    before_count = len(all_data['loads'])
    all_data['loads'] = all_data['loads'][all_data['loads']['load_id'].isin(valid_loads)].copy()
    after_count = len(all_data['loads'])
    deleted = before_count - after_count

    print(f"{'loads (via load_id)':<25} | {before_count:<10} | {after_count:<10} | {deleted:<10}")

print("-" * 70)
print(" تمت إعادة المزامنة بنجاح! الآن جميع الجداول متوافقة مع الـ ERD.")

 إعادة مزامنة البيانات (Data Synchronization Report):
----------------------------------------------------------------------
الجدول                    | قبل الحذف  | بعد الحذف  | المحذوف
----------------------------------------------------------------------
delivery_events           | 160916     | 160916     | 0
safety_incidents          | 165        | 165        | 0
fuel_purchases            | 185051     | 185051     | 0
loads (via load_id)       | 80458      | 80458      | 0
----------------------------------------------------------------------
 تمت إعادة المزامنة بنجاح! الآن جميع الجداول متوافقة مع الـ ERD.

تنظيف ومزامنة جدول drivers
2.   drivers

In [ ]:
# --- تنظيف وتجهيز جدول السائقين قبل المزامنة ---

# 1. عمل Trim لكل الأعمدة النصية في جدول السائقين (خاصة الـ ID والأسماء)
for col in ['driver_id', 'first_name', 'last_name']:
    all_data['drivers'][col] = all_data['drivers'][col].str.strip()

# 2. توحيد حالة الأحرف للأسماء (Title Case)
all_data['drivers']['first_name'] = all_data['drivers']['first_name'].str.title()
all_data['drivers']['last_name'] = all_data['drivers']['last_name'].str.title()

# 3. الآن نقوم بعملية المزامنة (بعد ضمان نظافة الـ IDs)
active_drivers = set(all_data['trips']['driver_id'])
initial_count = len(all_data['drivers'])

all_data['drivers'] = all_data['drivers'][all_data['drivers']['driver_id'].isin(active_drivers)].copy()

print(f"✅ تم تنظيف نصوص السائقين ومزامنتهم.")
print(f"   - عدد السائقين قبل الفلترة: {initial_count}")
print(f"   - السائقين المتبقين (الذين لديهم رحلات): {len(all_data['drivers'])}")

✅ تم تنظيف نصوص السائقين ومزامنتهم.
   - عدد السائقين قبل الفلترة: 150
   - السائقين المتبقين (الذين لديهم رحلات): 124

In [ ]:
# --- استكشاف جدول السائقين (Drivers Exploration) ---

print("📊 معلومات جدول السائقين (Drivers Info):")
print(all_data['drivers'].info())

print("\n" + "="*40 + "\n")

# فحص عينة من البيانات لرؤية شكل النصوص والتواريخ
print("👀 عينة من بيانات السائقين:")
display(all_data['drivers'].head())

print("\n" + "="*40 + "\n")

# فحص وجود قيم مفقودة في أعمدة هامة
print("🔍 عدد القيم المفقودة في كل عمود:")
print(all_data['drivers'].isnull().sum())

📊 معلومات جدول السائقين (Drivers Info):
<class 'pandas.core.frame.DataFrame'>
Index: 124 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          124 non-null    object
 1   first_name         124 non-null    object
 2   last_name          124 non-null    object
 3   hire_date          124 non-null    object
 4   termination_date   0 non-null      object
 5   license_number     124 non-null    object
 6   license_state      124 non-null    object
 7   date_of_birth      124 non-null    object
 8   home_terminal      124 non-null    object
 9   employment_status  124 non-null    object
 10  cdl_class          124 non-null    object
 11  years_experience   124 non-null    int64
dtypes: int64(1), object(11)
memory usage: 12.6+ KB
None

========================================

👀 عينة من بيانات السائقين:

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

========================================

🔍 عدد القيم المفقودة في كل عمود:
driver_id              0
first_name             0
last_name              0
hire_date              0
termination_date     124
license_number         0
license_state          0
date_of_birth          0
home_terminal          0
employment_status      0
cdl_class              0
years_experience       0
dtype: int64

In [ ]:
# --- تنظيف جدول السائقين (Drivers Table Cleaning) ---

# 1. تحويل التواريخ من نصوص إلى Datetime
date_cols = ['hire_date', 'date_of_birth']
for col in date_cols:
    all_data['drivers'][col] = pd.to_datetime(all_data['drivers'][col])

# 2. معالجة حالة السائقين النشطين
all_data['drivers']['termination_date'] = all_data['drivers']['termination_date'].fillna('Active')

# 3. توحيد نصوص الأسماء والولايات (Standardization)
all_data['drivers']['first_name'] = all_data['drivers']['first_name'].str.strip().str.title()
all_data['drivers']['last_name'] = all_data['drivers']['last_name'].str.strip().str.title()
all_data['drivers']['license_state'] = all_data['drivers']['license_state'].str.strip().str.upper()

# 4. تحويل الأعمدة الى category لتحسين الأداء (Categorical Data)
cat_cols = ['employment_status', 'license_state', 'cdl_class']
for col in cat_cols:
    all_data['drivers'][col] = all_data['drivers'][col].astype('category')

print("✅ تم تنظيف جدول السائقين بالكامل وتصنيف البيانات.")
print("-" * 30)
print(all_data['drivers'].info())

✅ تم تنظيف جدول السائقين بالكامل وتصنيف البيانات.
------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 124 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          124 non-null    object
 1   first_name         124 non-null    object
 2   last_name          124 non-null    object
 3   hire_date          124 non-null    datetime64[ns]
 4   termination_date   124 non-null    object
 5   license_number     124 non-null    object
 6   license_state      124 non-null    category
 7   date_of_birth      124 non-null    datetime64[ns]
 8   home_terminal      124 non-null    object
 9   employment_status  124 non-null    category
 10  cdl_class          124 non-null    category
 11  years_experience   124 non-null    int64
dtypes: category(3), datetime64[ns](2), int64(1), object(6)
memory usage: 11.0+ KB
None

In [ ]:
# 1. استبدال القيم المفقودة (NaN) بكلمة 'Active'
all_data['drivers']['termination_date'] = all_data['drivers']['termination_date'].fillna('Active')

# 2. عرض عينة للتأكد من ظهور الكلمة بدلاً من NaN
print("✅ شكل عمود تاريخ إنهاء الخدمة بعد المعالجة:")
display(all_data['drivers'][['driver_id', 'first_name', 'termination_date']].head())

✅ شكل عمود تاريخ إنهاء الخدمة بعد المعالجة:

  driver_id first_name termination_date
0  DRV00001   Jennifer           Active
1  DRV00002    William           Active
2  DRV00003    Charles           Active
3  DRV00004    Barbara           Active
4  DRV00005       Mary           Active

جدول الtrucks

In [ ]:
# --- 1. مرحلة الاستكشاف لجدول الشاحنات ---

print("📊 معلومات جدول الشاحنات (Trucks Info):")
print(all_data['trucks'].info())

print("\n" + "="*40 + "\n")

print("🔍 فحص القيم المفقودة (Nulls):")
print(all_data['trucks'].isnull().sum())

print("\n" + "="*40 + "\n")

print("👀 عينة من البيانات الأصلية (لقطة قبل التعديل):")
display(all_data['trucks'].head())

📊 معلومات جدول الشاحنات (Trucks Info):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    object
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    object
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    object
 5   acquisition_date       120 non-null    object
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    object
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    object
 10  home_terminal          120 non-null    object
dtypes: int64(4), object(7)
memory usage: 10.4+ KB
None

========================================

🔍 فحص القيم المفقودة (Nulls):
truck_id                 0
unit_number              0
make                     0
model_year               0
vin                      0
acquisition_date         0
acquisition_mileage      0
fuel_type                0
tank_capacity_gallons    0
status                   0
home_terminal            0
dtype: int64

========================================

👀 عينة من البيانات الأصلية (لقطة قبل التعديل):

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150,Maintenance,Atlanta
3,TRK00004,3317,Freightliner,2015,1VV131945381692351,2017-06-17,8875,Diesel,200,Active,Salt Lake City
4,TRK00005,6731,Freightliner,2016,1FT822215709701985,2021-10-08,42042,Diesel,250,Maintenance,Miami

In [ ]:
# --- مرحلة التنظيف لجدول الشاحنات (Trucks Cleaning) ---

# 1. تحويل تاريخ الاستحواذ لنوع Datetime
all_data['trucks']['acquisition_date'] = pd.to_datetime(all_data['trucks']['acquisition_date'])

# 2. تنظيف النصوص (إزالة المسافات وتوحيد حالة الأحرف للماركة)
all_data['trucks']['make'] = all_data['trucks']['make'].str.strip().str.upper()

# 3. تحويل الأعمدة التصنيفية لتحسين الأداء
for col in ['fuel_type', 'status', 'home_terminal']:
    all_data['trucks'][col] = all_data['trucks'][col].astype('category')

# 4. إضافة عمود "عمر الشاحنة" (اختياري لكنه احترافي جداً)
# حساب عدد السنوات منذ شراء الشاحنة وحتى اليوم
current_year = 2026 # بما أننا في عام 2026 حسب بيانات المشروع
all_data['trucks']['truck_age'] = current_year - all_data['trucks']['model_year']

print("✅ تم تنظيف جدول الشاحنات بنجاح.")
print("-" * 30)
# عرض النتيجة النهائية للأنواع
print(all_data['trucks'][['truck_id', 'acquisition_date', 'truck_age']].info())

✅ تم تنظيف جدول الشاحنات بنجاح.
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   truck_id          120 non-null    object
 1   acquisition_date  120 non-null    datetime64[ns]
 2   truck_age         120 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 2.9+ KB
None

fuel الوقود

📊 معلومات جدول الوقود (Fuel Info):
<class 'pandas.core.frame.DataFrame'>
Index: 185051 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  185051 non-null  object
 1   trip_id           185051 non-null  object
 2   truck_id          185051 non-null  object
 3   driver_id         185051 non-null  object
 4   purchase_date     185051 non-null  object
 5   location_city     185051 non-null  object
 6   location_state    185051 non-null  object
 7   gallons           185051 non-null  float64
 8   price_per_gallon  185051 non-null  float64
 9   total_cost        185051 non-null  float64
 10  fuel_card_number  185051 non-null  object
dtypes: float64(3), object(8)
memory usage: 16.9+ MB
None

========================================

🔍 فحص القيم المفقودة (Nulls):
fuel_purchase_id    0
trip_id             0
truck_id            0
driver_id           0
purchase_date       0
location_city       0
location_state      0
gallons             0
price_per_gallon    0
total_cost          0
fuel_card_number    0
dtype: int64

========================================

💰 فحص القيم الإحصائية (للتأكد من عدم وجود أسعار سالبة أو صفرية):

             gallons  price_per_gallon     total_cost
count  185051.000000     185051.000000  185051.000000
mean      124.807534          3.898667     486.632354
std        43.336867          0.436027     178.593691
min        50.000000          3.150000     158.500000
25%        87.200000          3.552000     336.240000
50%       124.600000          3.857000     480.600000
75%       162.300000          4.167000     625.660000
max       200.000000          5.000000     997.900000

In [ ]:
# --- مرحلة التنظيف لجدول الوقود (Fuel Cleaning) ---

# 1. تحويل تاريخ الشراء لنوع Datetime (ضروري جداً للتقارير الزمنية)
all_data['fuel_purchases']['purchase_date'] = pd.to_datetime(all_data['fuel_purchases']['purchase_date'])

# 2. تنظيف النصوص (المدينة والولاية)
all_data['fuel_purchases']['location_city'] = all_data['fuel_purchases']['location_city'].str.strip().str.title()
all_data['fuel_purchases']['location_state'] = all_data['fuel_purchases']['location_state'].str.strip().str.upper()

# 3. فحص منطقي سريع (Double Check)
# التأكد من أن التكلفة الكلية تساوي (الجالونات × سعر الجالون) بدقة
all_data['fuel_purchases']['calculated_cost'] = all_data['fuel_purchases']['gallons'] * all_data['fuel_purchases']['price_per_gallon']

# 4. تحويل الولاية لـ category لتسريع العمليات الجغرافية
all_data['fuel_purchases']['location_state'] = all_data['fuel_purchases']['location_state'].astype('category')

print("✅ تم تحويل تواريخ الوقود وتنظيف البيانات الجغرافية.")
print("-" * 30)
# عرض ملخص إحصائي سريع للتأكد من منطقية الأسعار
display(all_data['fuel_purchases'][['gallons', 'price_per_gallon', 'total_cost']].describe())

✅ تم تحويل تواريخ الوقود وتنظيف البيانات الجغرافية.
------------------------------

             gallons  price_per_gallon     total_cost
count  185051.000000     185051.000000  185051.000000
mean      124.807534          3.898667     486.632354
std        43.336867          0.436027     178.593691
min        50.000000          3.150000     158.500000
25%        87.200000          3.552000     336.240000
50%       124.600000          3.857000     480.600000
75%       162.300000          4.167000     625.660000
max       200.000000          5.000000     997.900000

جدول loads

In [ ]:
# --- خطوة 1: استكشاف جدول الأحمال (Loads Profiling) ---

print("📊 معلومات جدول الأحمال (Loads Info):")
print(all_data['loads'].info())

print("\n" + "="*40 + "\n")

print("🔍 فحص القيم المفقودة (Nulls):")
print(all_data['loads'].isnull().sum())

print("\n" + "="*40 + "\n")

# عرض عينة عشوائية للتأكد من تناسق النصوص
print("👀 عينة من البيانات (للملاحظة بالعين):")
display(all_data['loads'].sample(5))

📊 معلومات جدول الأحمال (Loads Info):
<class 'pandas.core.frame.DataFrame'>
Index: 80458 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              80458 non-null  object
 1   customer_id          80458 non-null  object
 2   route_id             80458 non-null  object
 3   load_date            80458 non-null  object
 4   load_type            80458 non-null  object
 5   weight_lbs           80458 non-null  int64
 6   pieces               80458 non-null  int64
 7   revenue              80458 non-null  float64
 8   fuel_surcharge       80458 non-null  float64
 9   accessorial_charges  80458 non-null  int64
 10  load_status          80458 non-null  object
 11  booking_type         80458 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 8.0+ MB
None

========================================

🔍 فحص القيم المفقودة (Nulls):
load_id                0
customer_id            0
route_id               0
load_date              0
load_type              0
weight_lbs             0
pieces                 0
revenue                0
fuel_surcharge         0
accessorial_charges    0
load_status            0
booking_type           0
dtype: int64

========================================

👀 عينة من البيانات (للملاحظة بالعين):

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
6660,LOAD00006661,CUST00187,RTE00040,2022-03-27,Refrigerated,43593,6,3928.24,524.70,0,Completed,Dedicated
10572,LOAD00010573,CUST00056,RTE00016,2022-05-16,Dry Van,26112,22,7033.98,463.93,0,Completed,Contract
64076,LOAD00064077,CUST00107,RTE00008,2024-04-03,Dry Van,41781,13,2271.83,114.30,0,Completed,Spot
63797,LOAD00063798,CUST00111,RTE00034,2024-03-31,Refrigerated,29595,27,5467.86,792.88,0,Completed,Contract
8946,LOAD00008947,CUST00144,RTE00021,2022-04-25,Dry Van,33782,2,4709.83,590.24,0,Completed,Dedicated

In [ ]:
# --- مرحلة التنظيف لجدول الأحمال (Loads Cleaning) ---

# 1. تحويل تاريخ التحميل لنوع Datetime
all_data['loads']['load_date'] = pd.to_datetime(all_data['loads']['load_date'])

# 2. تنظيف النصوص (إزالة المسافات وتوحيد حالة الأحرف)
text_cols = ['load_type', 'load_status', 'booking_type']
for col in text_cols:
    all_data['loads'][col] = all_data['loads'][col].str.strip().str.title()

# 3. تحويل الأعمدة المتكررة لنوع Category لتحسين الأداء
for col in text_cols:
    all_data['loads'][col] = all_data['loads'][col].astype('category')

# 4. إضافة عمود "إجمالي الإيرادات" (Total Revenue)
# يشمل الإيراد الأساسي + رسوم الوقود + الرسوم الإضافية
all_data['loads']['total_load_revenue'] = (
    all_data['loads']['revenue'] +
    all_data['loads']['fuel_surcharge'] +
    all_data['loads']['accessorial_charges']
)

print("✅ تم تحويل التواريخ، تنظيف النصوص، وحساب إجمالي الإيرادات لكل شحنة.")
print("-" * 30)
# عرض ملخص إحصائي للإيرادات للتأكد من منطقية الأرقام
display(all_data['loads'][['revenue', 'total_load_revenue']].describe())

✅ تم تحويل التواريخ، تنظيف النصوص، وحساب إجمالي الإيرادات لكل شحنة.
------------------------------

            revenue  total_load_revenue
count  80458.000000        80458.000000
mean    3073.353587         3495.711917
std     1884.013348         2074.880069
min      125.930000          141.570000
25%     1443.097500         1695.055000
50%     2826.830000         3218.030000
75%     4322.755000         4930.217500
max     8125.220000         9136.760000

الصيانة

In [ ]:
# --- خطوة 1: استكشاف جدول الصيانة (Maintenance Profiling) ---

print("📊 معلومات جدول الصيانة (Maintenance Info):")
print(all_data['maintenance_logs'].info())

print("\n" + "="*40 + "\n")

print("🔍 فحص القيم المفقودة (Nulls):")
print(all_data['maintenance_logs'].isnull().sum())

print("\n" + "="*40 + "\n")

# فحص أنواع الصيانة وتكلفتها
print("💰 عينة من سجلات الصيانة والتكاليف:")
display(all_data['maintenance_logs'][['maintenance_type', 'maintenance_cost', 'maintenance_date']].head())

📊 معلومات جدول الصيانة (Maintenance Info):

KeyError: 'maintenance_logs'

In [ ]:
print(all_data.keys())

In [ ]:
# --- خطوة 1: استكشاف جدول الصيانة ---
table_name = 'maintenance_records'

print(f"📊 معلومات جدول الصيانة ({table_name}):")
print(all_data[table_name].info())

print("\n🔍 فحص القيم المفقودة (Nulls):")
print(all_data[table_name].isnull().sum())

# --- خطوة 2: تنظيف الجدول بناءً على المعطيات المتوقعة ---
# 1. تحويل التاريخ
all_data[table_name]['maintenance_date'] = pd.to_datetime(all_data[table_name]['maintenance_date'])

# 2. تنظيف النصوص (إزالة مسافات وتوحيد حالة الأحرف)
all_data[table_name]['maintenance_type'] = all_data[table_name]['maintenance_type'].str.strip().str.title()

# 3. مزامنة مع الشاحنات السليمة فقط
valid_trucks = set(all_data['trucks']['truck_id'])
all_data[table_name] = all_data[table_name][all_data[table_name]['truck_id'].isin(valid_trucks)].copy()

print(f"\n✅ تم تنظيف {table_name} ومزامنته.. المتبقي: {len(all_data[table_name])} سجل.")
display(all_data[table_name].head(3))

In [ ]:
# --- مرحلة التنظيف لجدول سجلات الصيانة (Maintenance Records Cleaning) ---

# 1. تحويل التاريخ لنوع Datetime
all_data['maintenance_records']['maintenance_date'] = pd.to_datetime(all_data['maintenance_records']['maintenance_date'])

# 2. تنظيف النصوص (إزالة مسافات وتوحيد حالة الأحرف)
text_cols = ['maintenance_type', 'facility_location', 'service_description']
for col in text_cols:
    all_data['maintenance_records'][col] = all_data['maintenance_records'][col].str.strip().str.title()

# 3. التحقق المنطقي من التكاليف (Cross-Check)
# التأكد من أن التكلفة الكلية = تكلفة العمالة + تكلفة القطع
all_data['maintenance_records']['calculated_total'] = (
    all_data['maintenance_records']['labor_cost'] +
    all_data['maintenance_records']['parts_cost']
)

# 4. المزامنة مع قائمة الشاحنات السليمة (لضمان الدقة)
valid_truck_ids = set(all_data['trucks']['truck_id'])
all_data['maintenance_records'] = all_data['maintenance_records'][all_data['maintenance_records']['truck_id'].isin(valid_truck_ids)].copy()

print(f"✅ تم تنظيف سجلات الصيانة ومزامنتها.. المتبقي: {len(all_data['maintenance_records'])} سجل.")
print("-" * 30)
# عرض ملخص سريع لساعات التعطل والتكاليف
display(all_data['maintenance_records'][['downtime_hours', 'total_cost', 'calculated_total']].describe())

جدول 7

In [ ]:
# --- خطوة 1: استكشاف جدول الحوادث (Safety Incidents Profiling) ---

print("📊 معلومات جدول الحوادث (Safety Incidents Info):")
print(all_data['safety_incidents'].info())

print("\n" + "="*40 + "\n")

print("🔍 فحص القيم المفقودة (Nulls):")
print(all_data['safety_incidents'].isnull().sum())

print("\n" + "="*40 + "\n")

# عرض عينة لرؤية أوصاف الحوادث وتواريخها
print("👀 عينة من سجلات الحوادث:")
display(all_data['safety_incidents'][['incident_date', 'incident_type', 'severity_level', 'driver_id']].head())

In [ ]:
# فحص أسماء الأعمدة الفعلية لجدول الحوادث
print("📋 الأعمدة الموجودة في جدول الحوادث هي:")
print(all_data['safety_incidents'].columns.tolist())

print("\n" + "="*40 + "\n")

# عرض أول صفين لاستكشاف شكل البيانات
display(all_data['safety_incidents'].head(2))

In [ ]:
# --- مرحلة التنظيف لجدول الحوادث (Safety Incidents Cleaning) ---

# 1. تحويل التاريخ لنوع Datetime
all_data['safety_incidents']['incident_date'] = pd.to_datetime(all_data['safety_incidents']['incident_date'])

# 2. تنظيف النصوص (إزالة مسافات وتوحيد حالة الأحرف)
text_cols = ['incident_type', 'location_city', 'location_state', 'description']
for col in text_cols:
    all_data['safety_incidents'][col] = all_data['safety_incidents'][col].str.strip().str.title()

# 3. معالجة القيم المفقودة في الوصف (لو وجدت)
all_data['safety_incidents']['description'] = all_data['safety_incidents']['description'].fillna('No Description Provided')

# 4. تحويل أعمدة الـ Flag (Y/N) إلى Category لتحسين الأداء
flag_cols = ['at_fault_flag', 'injury_flag', 'preventable_flag']
for col in flag_cols:
    all_data['safety_incidents'][col] = all_data['safety_incidents'][col].astype('category')

# 5. حساب إجمالي خسائر الحادث (Total Loss)
# جمع (تلف المركبة + تلف الشحنة)
all_data['safety_incidents']['total_incident_loss'] = (
    all_data['safety_incidents']['vehicle_damage_cost'] +
    all_data['safety_incidents']['cargo_damage_cost']
)

# 6. المزامنة مع السائقين السليمين
valid_drivers = set(all_data['drivers']['driver_id'])
all_data['safety_incidents'] = all_data['safety_incidents'][all_data['safety_incidents']['driver_id'].isin(valid_drivers)].copy()

print(f"✅ تم تنظيف جدول الحوادث بنجاح.. المتبقي: {len(all_data['safety_incidents'])} حادث.")
print("-" * 30)
# عرض ملخص مالي للخسائر الناتجة عن الحوادث
display(all_data['safety_incidents'][['vehicle_damage_cost', 'cargo_damage_cost', 'total_incident_loss']].describe())

# جدول الطرق route

In [ ]:
# --- استكشاف جدول المسارات (Routes Profiling) ---
print("\n" + "="*50 + "\n")
print("📊 معلومات جدول المسارات (Routes Info):")
print(all_data['routes'].info())

print("\n🔍 فحص القيم المفقودة (Nulls):")
print(all_data['routes'].isnull().sum())

# عرض عينة
display(all_data['routes'].head(3))

In [ ]:
# --- مرحلة التنظيف لجدول المسارات (Routes Cleaning) ---

# 1. تنظيف النصوص (إزالة مسافات وتوحيد حالة الأحرف للمدن والولايات)
text_cols = ['origin_city', 'origin_state', 'destination_city', 'destination_state']
for col in text_cols:
    all_data['routes'][col] = all_data['routes'][col].str.strip().str.title()

# 2. توحيد اختصارات الولايات (لتكون حروف كبيرة دائماً)
all_data['routes']['origin_state'] = all_data['routes']['origin_state'].str.upper()
all_data['routes']['destination_state'] = all_data['routes']['destination_state'].str.upper()

# 3. إضافة عمود "إجمالي السعر للميل" (Total Rate per Mile)
# يجمع السعر الأساسي + ضريبة الوقود
all_data['routes']['total_rate_per_mile'] = (
    all_data['routes']['base_rate_per_mile'] +
    all_data['routes']['fuel_surcharge_rate']
)

# 4. حساب "تكلفة الرحلة الكاملة" المقدرة لهذا المسار
all_data['routes']['estimated_route_revenue'] = (
    all_data['routes']['typical_distance_miles'] * all_data['routes']['total_rate_per_mile']
)

print("✅ تم تنظيف نصوص المسارات وحساب التقديرات المالية لكل مسار.")
print("-" * 30)
# عرض عينة من المسارات مع التكلفة المقدرة
display(all_data['routes'][['route_id', 'origin_city', 'destination_city', 'estimated_route_revenue']].head())

المرافق 9

In [ ]:
# --- استكشاف جدول المرافق (Facilities Profiling) ---
print("\n" + "="*50 + "\n")
print("📋 أعمدة جدول المرافق:")
print(all_data['facilities'].columns.tolist())

print("\n📊 فحص الأنواع والقيم المفقودة:")
display(all_data['facilities'].info())
display(all_data['facilities'].isnull().sum())

In [ ]:
# --- مرحلة التنظيف لجدول المرافق (Facilities Cleaning) ---

# 1. تنظيف النصوص (إزالة مسافات وتوحيد حالة الأحرف)
text_cols = ['facility_name', 'facility_type', 'city', 'state']
for col in text_cols:
    all_data['facilities'][col] = all_data['facilities'][col].str.strip().str.title()

# 2. توحيد اختصار الولاية (حروف كبيرة)
all_data['facilities']['state'] = all_data['facilities']['state'].str.upper()

# 3. تحويل نوع المرفق لـ Category (لأن الأنواع محدودة مثل Warehouse, Terminal)
all_data['facilities']['facility_type'] = all_data['facilities']['facility_type'].astype('category')

# 4. تنظيف عمود ساعات العمل (إزالة أي مسافات زائدة)
all_data['facilities']['operating_hours'] = all_data['facilities']['operating_hours'].str.strip()

print("✅ تم تنظيف نصوص جدول المرافق وتصنيف الأنواع.")
print("-" * 30)
# عرض عينة للتأكد من نظافة التنسيق
display(all_data['facilities'][['facility_name', 'facility_type', 'city', 'operating_hours']].head())

التريلات

In [ ]:
# --- استكشاف جدول المقطورات (Trailers Profiling) ---
print("\n" + "="*50 + "\n")
print("📋 أعمدة جدول المقطورات:")
print(all_data['trailers'].columns.tolist())

print("\n📊 فحص الأنواع والقيم المفقودة:")
display(all_data['trailers'].info())
print(all_data['trailers'].isnull().sum())

In [ ]:
# --- مرحلة التنظيف لجدول المقطورات (Trailers Cleaning) ---

# 1. تحويل التاريخ لنوع Datetime
all_data['trailers']['acquisition_date'] = pd.to_datetime(all_data['trailers']['acquisition_date'])

# 2. تنظيف النصوص (Trim وتوحيد حالة الأحرف)
text_cols = ['trailer_type', 'status', 'current_location']
for col in text_cols:
    all_data['trailers'][col] = all_data['trailers'][col].str.strip().str.title()

# 3. تحويل الأعمدة المتكررة لنوع Category
for col in ['trailer_type', 'status']:
    all_data['trailers'][col] = all_data['trailers'][col].astype('category')

# 4. حساب عمر المقطورة (Asset Age)
current_year = 2026
all_data['trailers']['trailer_age'] = current_year - all_data['trailers']['model_year']

print("✅ تم تنظيف نصوص المقطورات، تحويل التواريخ، وحساب عمر الأصول.")
print("-" * 30)
# عرض عينة للتأكد من النتائج
display(all_data['trailers'][['trailer_id', 'trailer_type', 'length_feet', 'trailer_age']].head())

التسليم Delivery Events

In [ ]:
# --- استكشاف جدول أحداث التسليم (Delivery Events Profiling) ---
print("\n" + "="*50 + "\n")
print("📋 أعمدة جدول أحداث التسليم:")
print(all_data['delivery_events'].columns.tolist())

print("\n📊 فحص الأنواع والقيم المفقودة:")
display(all_data['delivery_events'].info())
print(all_data['delivery_events'].isnull().sum())

In [ ]:
# --- مرحلة التنظيف لجدول أحداث التسليم (Delivery Events Cleaning) ---

# 1. تحويل التواريخ المجدولة والفعلية لنوع Datetime
all_data['delivery_events']['scheduled_datetime'] = pd.to_datetime(all_data['delivery_events']['scheduled_datetime'])
all_data['delivery_events']['actual_datetime'] = pd.to_datetime(all_data['delivery_events']['actual_datetime'])

# 2. تنظيف النصوص (إزالة مسافات وتوحيد حالة الأحرف)
text_cols = ['event_type', 'location_city', 'location_state']
for col in text_cols:
    all_data['delivery_events'][col] = all_data['delivery_events'][col].str.strip().str.title()

# 3. توحيد اختصار الولاية (حروف كبيرة)
all_data['delivery_events']['location_state'] = all_data['delivery_events']['location_state'].str.upper()

# 4. حساب "فرق التأخير" بالدقائق (Delay Minutes)
# إذا كان الرقم موجباً يعني تأخير، سالباً يعني وصول مبكر
all_data['delivery_events']['arrival_delay_minutes'] = (
    all_data['delivery_events']['actual_datetime'] - all_data['delivery_events']['scheduled_datetime']
).dt.total_seconds() / 60

print(f"✅ تم تنظيف {len(all_data['delivery_events'])} حدث تسليم وحساب فروق التوقيت.")
print("-" * 30)
# عرض عينة للتأكد من منطقية التأخير
display(all_data['delivery_events'][['event_type', 'on_time_flag', 'arrival_delay_minutes']].head())

In [ ]:
# إضافة عمود يوضح الحالة بناءً على الرقم
def get_status(delay):
    if delay > 0:
        return 'Late'
    elif delay < 0:
        return 'Early'
    else:
        return 'Exactly on Time'

all_data['delivery_events']['arrival_status'] = all_data['delivery_events']['arrival_delay_minutes'].apply(get_status)

# عرض العينة مرة أخرى لرؤية الفرق
display(all_data['delivery_events'][['event_type', 'arrival_delay_minutes', 'arrival_status', 'on_time_flag']].head())

جدول العملاء

In [ ]:
# --- استكشاف جدول العملاء (Customers Profiling) ---

table_name = 'customers'

if table_name in all_data:
    print(f"📋 أعمدة جدول {table_name}:")
    print(all_data[table_name].columns.tolist())

    print("\n📊 فحص الأنواع والقيم المفقودة:")
    print(all_data[table_name].info())

    print("\n🔍 عدد القيم المفقودة:")
    print(all_data[table_name].isnull().sum())

    print("\n👀 عينة من البيانات:")
    display(all_data[table_name].head(3))

In [ ]:
# --- مرحلة التنظيف لجدول العملاء (Customers Cleaning) ---

# 1. تحويل تاريخ بدء العقد لنوع Datetime
all_data['customers']['contract_start_date'] = pd.to_datetime(all_data['customers']['contract_start_date'])

# 2. تنظيف النصوص (Trim وتوحيد حالة الأحرف)
text_cols = ['customer_name', 'customer_type', 'primary_freight_type', 'account_status']
for col in text_cols:
    all_data['customers'][col] = all_data['customers'][col].str.strip().str.title()

# 3. تحويل الأعمدة التصنيفية لـ Category (لتحسين الأداء)
for col in ['customer_type', 'account_status']:
    all_data['customers'][col] = all_data['customers'][col].astype('category')

# 4. إضافة عمود "سنوات التعامل" (Customer Tenure)
# لمعرفة كم سنة مضت على توقيع العقد مع العميل
current_year = 2026
all_data['customers']['years_with_us'] = current_year - all_data['customers']['contract_start_date'].dt.year

print("✅ تم تنظيف نصوص العملاء وحساب أقدمية التعاقد.")
print("-" * 30)
# عرض ملخص لأهم العملاء بناءً على الإيراد المتوقع
display(all_data['customers'][['customer_name', 'annual_revenue_potential', 'years_with_us']].sort_values(by='annual_revenue_potential', ascending=False).head())

metrics driver

In [ ]:
# --- استكشاف جدول ادارة السائقين الشهرية ---
table_name = 'driver_monthly_metrics'

print(f"📋 أعمدة جدول {table_name}:")
print(all_data[table_name].columns.tolist())

print("\n📊 فحص الأنواع والقيم المفقودة:")
display(all_data[table_name].info())
display(all_data[table_name].isnull().sum())

In [ ]:
# --- مرحلة التنظيف لجدول مقاييس السائقين (Driver Metrics Cleaning) ---

# 1. تحويل الشهر لنوع Datetime
all_data['driver_monthly_metrics']['month'] = pd.to_datetime(all_data['driver_monthly_metrics']['month'])

# 2. مزامنة البيانات مع قائمة السائقين السليمين (Valid Drivers)
valid_drivers = set(all_data['drivers']['driver_id'])
all_data['driver_monthly_metrics'] = all_data['driver_monthly_metrics'][all_data['driver_monthly_metrics']['driver_id'].isin(valid_drivers)].copy()

# 3. إضافة عمود "الإيراد لكل ميل" (Revenue Per Mile)
# مقياس مهم جداً للمدرب لتقييم ربحية رحلات كل سائق
all_data['driver_monthly_metrics']['revenue_per_mile'] = (
    all_data['driver_monthly_metrics']['total_revenue'] /
    all_data['driver_monthly_metrics']['total_miles']
).replace([np.inf, -np.inf], 0) # لتجنب القسمة على صفر

print(f"✅ تم تنظيف مقاييس السائقين.. المتبقي: {len(all_data['driver_monthly_metrics'])} سجل شهري.")
print("-" * 30)
# عرض أفضل 5 سائقين من حيث معدل الالتزام بالمواعيد
display(all_data['driver_monthly_metrics'][['driver_id', 'month', 'on_time_delivery_rate', 'revenue_per_mile']].sort_values(by='on_time_delivery_rate', ascending=False).head())

14

In [ ]:
# --- استكشاف جدول كفاءة الشاحنات (Final Table) ---
table_name = 'truck_utilization_metrics'

print(f"📋 أعمدة جدول {table_name}:")
print(all_data[table_name].columns.tolist())

print("\n📊 فحص الأنواع والقيم المفقودة:")
display(all_data[table_name].info())
print(all_data[table_name].isnull().sum())

In [ ]:

# 1. تنظيف جدول كفاءة الشاحنات
all_data['truck_utilization_metrics']['month'] = pd.to_datetime(all_data['truck_utilization_metrics']['month'])

# مزامنة مع الشاحنات السليمة فقط
valid_trucks = set(all_data['trucks']['truck_id'])
all_data['truck_utilization_metrics'] = all_data['truck_utilization_metrics'][
    all_data['truck_utilization_metrics']['truck_id'].isin(valid_trucks)
].copy()

# 2. إضافة KPI جديد: "تكلفة الصيانة لكل ميل" (Maintenance Cost per Mile)
all_data['truck_utilization_metrics']['maint_cost_per_mile'] = (
    all_data['truck_utilization_metrics']['maintenance_cost'] /
    all_data['truck_utilization_metrics']['total_miles']
).replace([np.inf, -np.inf], 0).fillna(0)

print("✅ تم تنظيف آخر جدول بنجاح!")
print("-" * 30)

# 💾 حفظ جميع الجداول (الـ 14) في ملف Excel واحد نظيف جداً
output_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Cleaned_Fleet_Data_Final.xlsx'

with pd.ExcelWriter(output_path) as writer:
    for table_name, df in all_data.items():
        df.to_excel(writer, sheet_name=table_name, index=False)

print(f"🎉 تم حفظ قاعدة البيانات النظيفة بالكامل في:\n🔗 {output_path}")

In [ ]:
import os

# 1. تحديد مسار المجلد الجديد على الدرايف
folder_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Final_Cleaned_Excel_Files'

# 2. إنشاء المجلد إذا لم يكن موجوداً
if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"📁 تم إنشاء المجلد: {folder_path}")

# 3. حفظ كل جدول في ملف Excel منفصل (.xlsx)
for table_name, df in all_data.items():
    # بناء اسم الملف
    file_name = f"{table_name}_cleaned.xlsx"
    full_save_path = os.path.join(folder_path, file_name)

    # حفظ الملف (بدون الـ Index ليكون الجدول نظيفاً)
    df.to_excel(full_save_path, index=False)
    print(f"✅ تم حفظ الملف: {file_name}")

print("\n🎉 رائعة! الآن لديكِ 14 ملف Excel جاهزة تماماً في مجلد واحد.")

In [ ]:
import pandas as pd

# إنشاء قائمة لتخزين ملخص التنظيف
cleaning_summary = []

# المرور على كل الجداول في القاموس وحساب الإحصائيات
for table_name, df in all_data.items():
    cleaning_summary.append({
        "Table Name": table_name,
        "Cleaned Rows": len(df),
        "Total Columns": len(df.columns),
        "Status": "✅ Cleaned & Verified"
    })

# تحويل القائمة إلى DataFrame لسهولة العرض
summary_df = pd.DataFrame(cleaning_summary)

# إضافة سطر إجمالي في النهاية
total_rows = summary_df['Cleaned Rows'].sum()

print("="*60)
print(f" تقرير معالجة البيانات النهائي - مشروع DEPI")
print(f" إجمالي الجداول المعالجة: {len(summary_df)}")
print(f" إجمالي الصفوف النظيفة: {total_rows:,}")
print("="*60)

# عرض الجدول بشكل منسق
display(summary_df.style.set_properties(**{
    'background-color': '#f9f9f9',
    'color': '#2c3e50',
    'border-color': 'white'
}))

In [ ]:
# 1. جلب البيانات الأصلية للسائقين (قبل المزامنة والحذف)
# تأكدي من أن المسار هو نفس مسار ملف السائقين الأصلي عندك
original_drivers = pd.read_csv('/content/drive/MyDrive/Data Analysis DEPI Project/drivers.csv')

# 2. تحديد السائقين الحاليين (الـ 124 النشطين)
active_drivers_ids = all_data['drivers']['driver_id'].unique()

# 3. استخراج السائقين الذين لم يعد لهم وجود في البيانات النظيفة (الـ 26 سائق)
terminated_drivers = original_drivers[~original_drivers['driver_id'].isin(active_drivers_ids)].copy()

# 4. معالجة التواريخ وحساب سنوات الخبرة
# نحول التواريخ لصيغة صحيحة
terminated_drivers['hire_date'] = pd.to_datetime(terminated_drivers['hire_date'])
# تاريخ اليوم للقياس (بناءً على زمن البيانات)
analysis_date = pd.to_datetime('2024-12-31')

terminated_drivers['years_at_company'] = ((analysis_date - terminated_drivers['hire_date']).dt.days / 365.25).round(1)

# 5. عرض التقرير
print(f"📌 تم تحديد {len(terminated_drivers)} سائق خارج الخدمة (Terminated/Inactive)")
display(terminated_drivers[['driver_id', 'full_name', 'hire_date', 'years_at_company']].sort_values(by='years_at_company', ascending=False))

In [ ]:
import pandas as pd
import os

# 1. تحديد المسار
folder_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/'
file_path = os.path.join(folder_path, 'drivers.csv')

if os.path.exists(file_path):
    # 2. قراءة الملف الأصلي
    original_drivers = pd.read_csv(file_path)

    # 3. دمج الاسم الأول والأخير (لأن 'full_name' غير موجود في الملف الخام)
    if 'first_name' in original_drivers.columns and 'last_name' in original_drivers.columns:
        original_drivers['full_name'] = original_drivers['first_name'] + ' ' + original_drivers['last_name']

    # 4. تحديد السائقين الحاليين (النشطين)
    active_drivers_ids = all_data['drivers']['driver_id'].unique()

    # 5. استخراج السائقين الـ 26 الذين غادروا
    terminated_drivers = original_drivers[~original_drivers['driver_id'].isin(active_drivers_ids)].copy()

    # 6. حساب سنوات الخبرة
    terminated_drivers['hire_date'] = pd.to_datetime(terminated_drivers['hire_date'])
    analysis_date = pd.to_datetime('2024-12-31')
    terminated_drivers['years_at_company'] = ((analysis_date - terminated_drivers['hire_date']).dt.days / 365.25).round(1)

    print(f"✅ تم تحديد {len(terminated_drivers)} سائق (Inactive/Terminated).")

    # عرض الأعمدة المتاحة لضمان عدم حدوث خطأ
    cols_to_show = ['driver_id', 'full_name', 'hire_date', 'years_at_company']
    display(terminated_drivers[cols_to_show].sort_values(by='years_at_company', ascending=False))

else:
    print(f"❌ لم يتم العثور على الملف في المسار: {file_path}")

In [ ]:
import pandas as pd
import os

# 1. تحديد المسار الأساسي
base_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/'

# 2. قائمة بالملفات التي نريد فحص أعمدتها والـ Nulls فيها
files_to_audit = {
    'Fuel': 'fuel_purchases.csv',
    'Trips': 'trips.csv',
    'Loads': 'loads.csv'
}

print("🔍 تقرير فحص جودة البيانات (Data Quality Audit):\n")

for label, file_name in files_to_check.items():
    file_path = os.path.join(base_path, file_name)

    if os.path.exists(file_path):
        df = pd.read_csv(file_path)

        print(f"📋 جدول [{label}]:")
        print(f"   - أسماء الأعمدة: {list(df.columns)}")

        # فحص الـ Nulls في هذا الجدول
        nulls = df.isnull().sum()
        actual_nulls = nulls[nulls > 0]

        if not actual_nulls.empty:
            print(f"   - ⚠️ تم العثور على قيم مفقودة (Nulls):")
            for col, count in actual_nulls.items():
                percentage = (count / len(df)) * 100
                print(f"     * عمود [{col}]: {count} قيمة فارغة ({percentage:.2f}%)")
        else:
            print("   - ✅ لا توجد قيم مفقودة في هذا الجدول.")
        print("-" * 50)
    else:
        print(f"❌ الملف {file_name} غير موجود في المسار المحدد.")

In [ ]:
import pandas as pd
import os

# 1. المسار الأساسي (تأكدي من وجود الشرطة المائلة في النهاية)
base_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/'

# 2. الحصول على قائمة بكل ملفات الـ CSV في المجلد
csv_files = [f for f in os.listdir(base_path) if f.endswith('.csv')]

# 3. إنشاء قائمة لتخزين النتائج
audit_results = []

print(f"🚀 بدء فحص {len(csv_files)} ملفاً في المجلد...\n")

for file_name in csv_files:
    file_path = os.path.join(base_path, file_name)
    df = pd.read_csv(file_path)

    # حساب الإحصائيات لكل ملف
    total_rows = len(df)
    null_counts = df.isnull().sum().sum() # إجمالي الـ Nulls في الجدول كله
    cols_with_nulls = df.columns[df.isnull().any()].tolist() # الأعمدة المصابة

    audit_results.append({
        'Table Name': file_name,
        'Total Rows': total_rows,
        'Total Columns': len(df.columns),
        'Total Nulls': null_counts,
        'Null Percentage': (null_counts / (total_rows * len(df.columns))) * 100,
        'Affected Columns': cols_with_nulls
    })

# 4. تحويل النتائج لجدول منظم
audit_df = pd.DataFrame(audit_results)

# 5. عرض النتائج مرتبة حسب الأكثر احتواءً على Nulls
print("📊 تقرير جودة البيانات الشامل:")
display(audit_df.sort_values(by='Total Nulls', ascending=False))

In [ ]:
import pandas as pd

# 1. تحميل جدول الوقود
fuel_df = pd.read_csv('/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases.csv')

# 2. فحص أسماء الأعمدة بدقة (للتأكد من عدم وجود مسافات مخفية)
print("📌 الأسماء الحقيقية للأعمدة في جدول الوقود:")
print(list(fuel_df.columns))
print("-" * 30)

# 3. تقرير تفصيلي للقيم المفقودة لكل عمود في جدول الوقود
fuel_nulls = fuel_df.isnull().sum()
fuel_report = pd.DataFrame({
    'Column Name': fuel_nulls.index,
    'Missing Values': fuel_nulls.values,
    'Percentage %': (fuel_nulls.values / len(fuel_df)) * 100
})

print("📊 فحص أعمدة جدول الوقود (Detailed Fuel Audit):")
display(fuel_report)

In [ ]:
import pandas as pd

# 1. تحميل الملف
fuel_df = pd.read_csv('/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases.csv')

# 2. حذف أي صفوف فارغة تماماً قد تكون في نهاية الملف
fuel_df = fuel_df.dropna(how='all')

# 3. التأكد من أن الأعمدة الحسابية أرقام فعلاً (أي نص سيتحول لـ Null ثم نعوضه)
cols_to_fix = ['gallons', 'price_per_gallon', 'total_cost']
for col in cols_to_fix:
    fuel_df[col] = pd.to_numeric(fuel_df[col], errors='coerce') # تحويل أي نص خطأ لـ Null
    # ملء أي Null ظهر بالمتوسط لضمان عدم رفض SQL
    fuel_df[col] = fuel_df[col].fillna(fuel_df[col].mean())

# 4. التعامل مع الـ IDs المفقودة (3988 قيمة)
# بما أن SQL يرفض الـ Null في الـ IDs، سنضع قيمة افتراضية مثل 'UNKNOWN'
fuel_df['driver_id'] = fuel_df['driver_id'].fillna('UNKNOWN')
fuel_df['truck_id'] = fuel_df['truck_id'].fillna('UNKNOWN')

# 5. حفظ الملف بصيغة نظيفة جداً وبدون فهرس
output_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases_v3_ready.csv'
fuel_df.to_csv(output_path, index=False)

print(f"✅ تم تجهيز الملف النهائي: {output_path}")

✅ تم تجهيز الملف النهائي: /content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases_v3_ready.csv

In [ ]:
import pandas as pd

# 1. تحميل ملف الوقود
file_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases.csv'
fuel_df = pd.read_csv(file_path)

# 2. حذف الصفوف التي تحتوي على Null في driver_id أو truck_id
# سنستخدم dropna ونحدد الأعمدة المستهدفة (subset)
fuel_df_cleaned = fuel_df.dropna(subset=['driver_id', 'truck_id']).copy()

# 3. التأكد من حذف أي صفوف وهمية فارغة تماماً (Ghost Rows)
fuel_df_cleaned = fuel_df_cleaned.dropna(how='all')

# 4. معالجة الأعمدة الحسابية (للتأكد من عدم وجود رموز غريبة تسبب رفض SQL)
cols_to_check = ['gallons', 'price_per_gallon', 'total_cost']
for col in cols_to_check:
    # تحويل العمود لرقم، وأي قيمة غير صالحة تتحول لـ NaN ثم تحذف
    fuel_df_cleaned[col] = pd.to_numeric(fuel_df_cleaned[col], errors='coerce')

# 5. حذف أي صفوف نتجت عن خطأ في التحويل الرقمي في الخطوة السابقة
fuel_df_cleaned = fuel_df_cleaned.dropna(subset=cols_to_check)

# 6. فحص نهائي للتأكد من نظافة البيانات
print(f"✅ عدد الصفوف قبل الحذف: {len(fuel_df)}")
print(f"✅ عدد الصفوف بعد الحذف: {len(fuel_df_cleaned)}")
print(f"✅ عدد القيم المفقودة الآن: {fuel_df_cleaned.isnull().sum().sum()}")

# 7. حفظ الملف بصيغة CSV نظيفة جداً
output_path = '/content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases_final_v4.csv'
fuel_df_cleaned.to_csv(output_path, index=False)

print(f"\n🚀 الملف جاهز للرفع الآن: {output_path}")

✅ عدد الصفوف قبل الحذف: 196442
✅ عدد الصفوف بعد الحذف: 188668
✅ عدد القيم المفقودة الآن: 0

🚀 الملف جاهز للرفع الآن: /content/drive/MyDrive/Data Analysis DEPI Project/Depi Final Project R/fuel_purchases_final_v4.csv