#Supply chain analysis

In [107]:
#Import Laibraries

import pandas as pd
import numpy as np

In [108]:
# Importing & Cleaning Loads Table 

loads_df=pd.read_csv('loads.csv')
loads_df.info()
loads_df['load_date']=pd.to_datetime(loads_df['load_date'])
loads_df.columns = loads_df.columns.str.strip()
loads_df.info()
loads_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  str
 1   customer_id          85410 non-null  str
 2   route_id             85410 non-null  str
 3   load_date            85410 non-null  str
 4   load_type            85410 non-null  str
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  str
 11  booking_type         85410 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 7.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  str
 1   customer_id          85410 non-null  str
 2   route_id             85410 non-null  str
 3   load_date            85410 non-null  datetime64[us]
 4   load_type            85410 non-null  str
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  str
 11  booking_type         85410 non-null  str
dtypes: datetime64[us](1), float64(2), int64(3), str(6)
memory usage: 7.8 MB

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot

In [109]:
# Importing & Cleaning customers Table
 
customers_df=pd.read_csv('customers.csv')
customers_df.info()
customers_df['contract_start_date']=pd.to_datetime(customers_df['contract_start_date'])
customers_df.columns = customers_df.columns.str.strip()
customers_df.info()
customers_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    str
 1   customer_name             200 non-null    str
 2   customer_type             200 non-null    str
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    str
 5   account_status            200 non-null    str
 6   contract_start_date       200 non-null    str
 7   annual_revenue_potential  200 non-null    int64
dtypes: int64(2), str(6)
memory usage: 12.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    str
 1   customer_name             200 non-null    str
 2   customer_type             200 non-null    str
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    str
 5   account_status            200 non-null    str
 6   contract_start_date       200 non-null    datetime64[us]
 7   annual_revenue_potential  200 non-null    int64
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 12.6 KB

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [110]:
# Importing & Cleaning drivers Table

drivers_df=pd.read_csv('drivers.csv')
drivers_df.info()
drivers_df['termination_date']=pd.to_datetime(drivers_df['termination_date'])
drivers_df['termination_date'] = drivers_df['termination_date'].fillna('On_Duty')
drivers_df['first_name'] = drivers_df['first_name'].str.title()
drivers_df['last_name'] = drivers_df['last_name'].str.title()
drivers_df.columns = drivers_df.columns.str.strip()
drivers_df.info()
drivers_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          150 non-null    str
 1   first_name         150 non-null    str
 2   last_name          150 non-null    str
 3   hire_date          150 non-null    str
 4   termination_date   26 non-null     str
 5   license_number     150 non-null    str
 6   license_state      150 non-null    str
 7   date_of_birth      150 non-null    str
 8   home_terminal      150 non-null    str
 9   employment_status  150 non-null    str
 10  cdl_class          150 non-null    str
 11  years_experience   150 non-null    int64
dtypes: int64(1), str(11)
memory usage: 14.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          150 non-null    str
 1   first_name         150 non-null    str
 2   last_name          150 non-null    str
 3   hire_date          150 non-null    str
 4   termination_date   150 non-null    object
 5   license_number     150 non-null    str
 6   license_state      150 non-null    str
 7   date_of_birth      150 non-null    str
 8   home_terminal      150 non-null    str
 9   employment_status  150 non-null    str
 10  cdl_class          150 non-null    str
 11  years_experience   150 non-null    int64
dtypes: int64(1), object(1), str(10)
memory usage: 14.2+ KB

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,On_Duty,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,On_Duty,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,On_Duty,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,On_Duty,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,On_Duty,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [111]:
# Importing & Cleaning delivery_events Table

delivery_events_df=pd.read_csv('delivery_events.csv')
delivery_events_df.info()
delivery_events_df['actual_datetime']=pd.to_datetime(delivery_events_df['actual_datetime'])
delivery_events_df['scheduled_datetime']=pd.to_datetime(delivery_events_df['scheduled_datetime'])
delivery_events_df['location_city'] = delivery_events_df['location_city'].str.title()
delivery_events_df.columns = delivery_events_df.columns.str.strip()
delivery_events_df.info()
delivery_events_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  str
 1   load_id             170820 non-null  str
 2   trip_id             170820 non-null  str
 3   event_type          170820 non-null  str
 4   facility_id         170820 non-null  str
 5   scheduled_datetime  170820 non-null  str
 6   actual_datetime     170820 non-null  str
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  str
 10  location_state      170820 non-null  str
dtypes: bool(1), int64(1), str(9)
memory usage: 13.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  str
 1   load_id             170820 non-null  str
 2   trip_id             170820 non-null  str
 3   event_type          170820 non-null  str
 4   facility_id         170820 non-null  str
 5   scheduled_datetime  170820 non-null  datetime64[us]
 6   actual_datetime     170820 non-null  datetime64[us]
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  str
 10  location_state      170820 non-null  str
dtypes: bool(1), datetime64[us](2), int64(1), str(7)
memory usage: 13.2 MB

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
4,EVT00000005,LOAD00000003,TRIP00000003,Pickup,FAC00001,2022-01-01 08:00:00.000000,2022-01-01 07:28:02.169634,83,True,Columbus,OH

In [112]:
# Importing & Cleaning driver_monthly_metrics Table

driver_monthly_metrics_df=pd.read_csv('driver_monthly_metrics.csv')
driver_monthly_metrics_df.info()
driver_monthly_metrics_df['month']=pd.to_datetime(driver_monthly_metrics_df['month'])
drivers_df.columns = drivers_df.columns.str.strip()
driver_monthly_metrics_df.info()
driver_monthly_metrics_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4464 non-null   str
 1   month                  4464 non-null   str
 2   trips_completed        4464 non-null   int64
 3   total_miles            4464 non-null   int64
 4   total_revenue          4464 non-null   float64
 5   average_mpg            4464 non-null   float64
 6   total_fuel_gallons     4464 non-null   float64
 7   on_time_delivery_rate  4464 non-null   float64
 8   average_idle_hours     4464 non-null   float64
dtypes: float64(5), int64(2), str(2)
memory usage: 314.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4464 non-null   str
 1   month                  4464 non-null   datetime64[us]
 2   trips_completed        4464 non-null   int64
 3   total_miles            4464 non-null   int64
 4   total_revenue          4464 non-null   float64
 5   average_mpg            4464 non-null   float64
 6   total_fuel_gallons     4464 non-null   float64
 7   on_time_delivery_rate  4464 non-null   float64
 8   average_idle_hours     4464 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(2), str(1)
memory usage: 314.0 KB

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,2022-04-01,19,28127,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,2022-05-01,14,16071,36256.82,6.35,2573.1,0.214,6.8

In [113]:
# Importing & Cleaning facilities Table

facilities_df=pd.read_csv('facilities.csv')
facilities_df['city'] = facilities_df['city'].str.title()
facilities_df['facility_name'] = facilities_df['facility_name'].str.title()
facilities_df['facility_type'] = facilities_df['facility_type'].str.title()
facilities_df.columns = facilities_df.columns.str.strip()
facilities_df.info()
facilities_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   facility_id      50 non-null     str
 1   facility_name    50 non-null     str
 2   facility_type    50 non-null     str
 3   city             50 non-null     str
 4   state            50 non-null     str
 5   latitude         50 non-null     float64
 6   longitude        50 non-null     float64
 7   dock_doors       50 non-null     int64
 8   operating_hours  50 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 3.6 KB

,facility_id,facility_name,facility_type,city,state,latitude,longitude,dock_doors,operating_hours
0,FAC00001,Houston Distribution Center,Cross-Dock,Houston,TX,29.7604,-95.3698,125,24/7
1,FAC00002,Kansas City Hub,Cross-Dock,Kansas City,MO,39.0997,-94.5786,33,7AM-7PM
2,FAC00003,Charlotte Distribution Center,Distribution Center,Charlotte,NC,35.2271,-80.8431,138,24/7
3,FAC00004,Chicago Distribution Center,Distribution Center,Chicago,IL,41.8781,-87.6298,38,8AM-5PM
4,FAC00005,Indianapolis Hub,Distribution Center,Indianapolis,IN,39.7684,-86.1581,56,8AM-5PM

In [114]:
# Importing & Cleaning fuel_purchases Table

fuel_purchases_df=pd.read_csv('fuel_purchases.csv')
fuel_purchases_df.info()
fuel_purchases_df=fuel_purchases_df.dropna()
fuel_purchases_df['purchase_date']=pd.to_datetime(fuel_purchases_df['purchase_date'])
fuel_purchases_df['location_city'] = fuel_purchases_df['location_city'].str.title()
fuel_purchases_df.columns = fuel_purchases_df.columns.str.strip()
fuel_purchases_df.info()
fuel_purchases_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 196442 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  196442 non-null  str
 1   trip_id           196442 non-null  str
 2   truck_id          192562 non-null  str
 3   driver_id         192454 non-null  str
 4   purchase_date     196442 non-null  str
 5   location_city     196442 non-null  str
 6   location_state    196442 non-null  str
 7   gallons           196442 non-null  float64
 8   price_per_gallon  196442 non-null  float64
 9   total_cost        196442 non-null  float64
 10  fuel_card_number  196442 non-null  str
dtypes: float64(3), str(8)
memory usage: 16.5 MB
<class 'pandas.DataFrame'>
Index: 188668 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  188668 non-null  str
 1   trip_id           188668 non-null  str
 2   truck_id          188668 non-null  str
 3   driver_id         188668 non-null  str
 4   purchase_date     188668 non-null  datetime64[us]
 5   location_city     188668 non-null  str
 6   location_state    188668 non-null  str
 7   gallons           188668 non-null  float64
 8   price_per_gallon  188668 non-null  float64
 9   total_cost        188668 non-null  float64
 10  fuel_card_number  188668 non-null  str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 17.3 MB

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816
3,FUEL00000004,TRIP00008465,TRK00018,DRV00047,2022-04-20 00:00:00,Memphis,NY,130.7,3.579,467.78,FC776357
5,FUEL00000006,TRIP00062650,TRK00012,DRV00104,2024-03-18 23:00:00,Dallas,NY,182.2,3.494,636.61,FC277504
6,FUEL00000007,TRIP00000851,TRK00072,DRV00127,2022-01-11 21:00:00,Miami,TX,146.3,3.914,572.62,FC256663

In [115]:
# Importing & Cleaning maintenance_records Table

maintenance_records_df=pd.read_csv('maintenance_records.csv')
maintenance_records_df.info()
maintenance_records_df['maintenance_date']=pd.to_datetime(maintenance_records_df['maintenance_date'])
maintenance_records_df['facility_location'] = maintenance_records_df['facility_location'].str.title()
maintenance_records_df.columns = maintenance_records_df.columns.str.strip()
maintenance_records_df.info()
maintenance_records_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   str
 1   truck_id             2920 non-null   str
 2   maintenance_date     2920 non-null   str
 3   maintenance_type     2920 non-null   str
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   str
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   str
dtypes: float64(5), int64(1), str(6)
memory usage: 273.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   str
 1   truck_id             2920 non-null   str
 2   maintenance_date     2920 non-null   datetime64[us]
 3   maintenance_type     2920 non-null   str
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   str
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   str
dtypes: datetime64[us](1), float64(5), int64(1), str(5)
memory usage: 273.9 KB

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive
3,MAINT00000004,TRK00056,2022-01-02,Inspection,416522,2.8,298.80,67.48,366.28,Kansas City,34.6,Emergency Inspection
4,MAINT00000005,TRK00029,2022-01-02,Repair,179968,4.6,409.08,982.59,1391.67,Omaha,4.4,Emergency Repair

In [116]:
# Importing & Cleaning routes Table

routes_df=pd.read_csv('routes.csv')
routes_df['destination_city'] = routes_df['destination_city'].str.title()
routes_df.columns = routes_df.columns.str.strip()
routes_df.info()
routes_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     str
 1   origin_city             58 non-null     str
 2   origin_state            58 non-null     str
 3   destination_city        58 non-null     str
 4   destination_state       58 non-null     str
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), str(5)
memory usage: 4.2 KB

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3

In [117]:
# Importing & Cleaning safety_incidents Table

safety_incidents_df=pd.read_csv('safety_incidents.csv')
safety_incidents_df.info()
safety_incidents_df=safety_incidents_df.dropna(subset=["truck_id","driver_id"])
safety_incidents_df['incident_date']=pd.to_datetime(safety_incidents_df['incident_date'])
safety_incidents_df['location_city'] = safety_incidents_df['location_city'].str.title()
safety_incidents_df.columns = safety_incidents_df.columns.str.strip()
safety_incidents_df.info()
safety_incidents_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   incident_id          170 non-null    str
 1   trip_id              170 non-null    str
 2   truck_id             169 non-null    str
 3   driver_id            169 non-null    str
 4   incident_date        170 non-null    str
 5   incident_type        170 non-null    str
 6   location_city        170 non-null    str
 7   location_state       170 non-null    str
 8   at_fault_flag        170 non-null    bool
 9   injury_flag          170 non-null    bool
 10  vehicle_damage_cost  170 non-null    float64
 11  cargo_damage_cost    170 non-null    float64
 12  claim_amount         170 non-null    float64
 13  preventable_flag     170 non-null    bool
 14  description          170 non-null    str
dtypes: bool(3), float64(3), str(9)
memory usage: 16.6 KB
<class 'pandas.DataFrame'>
Index: 168 entries, 0 to 169
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   incident_id          168 non-null    str
 1   trip_id              168 non-null    str
 2   truck_id             168 non-null    str
 3   driver_id            168 non-null    str
 4   incident_date        168 non-null    datetime64[us]
 5   incident_type        168 non-null    str
 6   location_city        168 non-null    str
 7   location_state       168 non-null    str
 8   at_fault_flag        168 non-null    bool
 9   injury_flag          168 non-null    bool
 10  vehicle_damage_cost  168 non-null    float64
 11  cargo_damage_cost    168 non-null    float64
 12  claim_amount         168 non-null    float64
 13  preventable_flag     168 non-null    bool
 14  description          168 non-null    str
dtypes: bool(3), datetime64[us](1), float64(3), str(8)
memory usage: 17.6 KB

,incident_id,trip_id,truck_id,driver_id,incident_date,incident_type,location_city,location_state,at_fault_flag,injury_flag,vehicle_damage_cost,cargo_damage_cost,claim_amount,preventable_flag,description
0,INC00000001,TRIP00036079,TRK00006,DRV00006,2023-04-09 14:00:00,Moving Violation,Columbus,PA,True,False,12629.26,0.00,12629.26,True,Severe incident involving equipment
1,INC00000002,TRIP00032462,TRK00084,DRV00006,2023-02-19 11:00:00,Moving Violation,Columbus,NC,False,False,2700.70,14284.24,16984.94,False,Severe incident involving weather
2,INC00000003,TRIP00067583,TRK00106,DRV00119,2024-05-20 01:00:00,Customer Complaint,Seattle,OK,True,False,24302.32,0.00,24302.32,True,Minor incident involving traffic
3,INC00000004,TRIP00049128,TRK00085,DRV00134,2023-09-26 03:00:00,Equipment Damage,Kansas City,TN,True,False,4879.13,0.00,4879.13,True,Moderate incident involving equipment
4,INC00000005,TRIP00062884,TRK00014,DRV00133,2024-03-20 14:00:00,DOT Violation,Las Vegas,IN,False,False,14951.40,0.00,14951.40,False,Minor incident involving other driver

In [118]:
# Importing & Cleaning trailers Table

trailers_df=pd.read_csv('trailers.csv')
trailers_df.info()
trailers_df['acquisition_date']=pd.to_datetime(trailers_df['acquisition_date'])
trailers_df.columns = trailers_df.columns.str.strip()
trailers_df.info()
trailers_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trailer_id        180 non-null    str
 1   trailer_number    180 non-null    int64
 2   trailer_type      180 non-null    str
 3   length_feet       180 non-null    int64
 4   model_year        180 non-null    int64
 5   vin               180 non-null    str
 6   acquisition_date  180 non-null    str
 7   status            180 non-null    str
 8   current_location  180 non-null    str
dtypes: int64(3), str(6)
memory usage: 12.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trailer_id        180 non-null    str
 1   trailer_number    180 non-null    int64
 2   trailer_type      180 non-null    str
 3   length_feet       180 non-null    int64
 4   model_year        180 non-null    int64
 5   vin               180 non-null    str
 6   acquisition_date  180 non-null    datetime64[us]
 7   status            180 non-null    str
 8   current_location  180 non-null    str
dtypes: datetime64[us](1), int64(3), str(5)
memory usage: 12.8 KB

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee
3,TRL00004,3910,Dry Van,53,2024,1AV544000060905105,2018-08-27,Active,New York
4,TRL00005,7524,Dry Van,53,2016,1AV170126369813275,2019-11-22,Active,Las Vegas

In [119]:
# Importing & Cleaning trips Table

trips_df=pd.read_csv('trips.csv')
trips_df.info()
trips_df['dispatch_date']=pd.to_datetime(trips_df['dispatch_date'])
trips_df=trips_df.dropna(subset=["driver_id","truck_id","trailer_id"])
trips_df.columns = trips_df.columns.str.strip()
trips_df.info()
trips_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                85410 non-null  str
 1   load_id                85410 non-null  str
 2   driver_id              83696 non-null  str
 3   truck_id               83738 non-null  str
 4   trailer_id             83730 non-null  str
 5   dispatch_date          85410 non-null  str
 6   actual_distance_miles  85410 non-null  int64
 7   actual_duration_hours  85410 non-null  float64
 8   fuel_gallons_used      85410 non-null  float64
 9   average_mpg            85410 non-null  float64
 10  idle_time_hours        85410 non-null  float64
 11  trip_status            85410 non-null  str
dtypes: float64(4), int64(1), str(7)
memory usage: 7.8 MB
<class 'pandas.DataFrame'>
Index: 80458 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                80458 non-null  str
 1   load_id                80458 non-null  str
 2   driver_id              80458 non-null  str
 3   truck_id               80458 non-null  str
 4   trailer_id             80458 non-null  str
 5   dispatch_date          80458 non-null  datetime64[us]
 6   actual_distance_miles  80458 non-null  int64
 7   actual_duration_hours  80458 non-null  float64
 8   fuel_gallons_used      80458 non-null  float64
 9   average_mpg            80458 non-null  float64
 10  idle_time_hours        80458 non-null  float64
 11  trip_status            80458 non-null  str
dtypes: datetime64[us](1), float64(4), int64(1), str(6)
memory usage: 8.0 MB

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed
3,TRIP00000004,LOAD00000004,DRV00083,TRK00105,TRL00018,2022-01-01,717,11.1,110.3,6.50,9.6,Completed
4,TRIP00000005,LOAD00000005,DRV00044,TRK00076,TRL00054,2022-01-01,2243,35.0,328.9,6.82,11.6,Completed

In [120]:
# Importing & Cleaning truck_utilization_metrics Table

truck_utilization_metrics_df=pd.read_csv('truck_utilization_metrics.csv')
truck_utilization_metrics_df.info()
truck_utilization_metrics_df['month']=pd.to_datetime(truck_utilization_metrics_df['month'])
truck_utilization_metrics_df.columns = truck_utilization_metrics_df.columns.str.strip()
truck_utilization_metrics_df.info()
truck_utilization_metrics_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   truck_id            3312 non-null   str
 1   month               3312 non-null   str
 2   trips_completed     3312 non-null   int64
 3   total_miles         3312 non-null   int64
 4   total_revenue       3312 non-null   float64
 5   average_mpg         3312 non-null   float64
 6   maintenance_events  3312 non-null   int64
 7   maintenance_cost    3312 non-null   float64
 8   downtime_hours      3312 non-null   float64
 9   utilization_rate    3312 non-null   float64
dtypes: float64(5), int64(3), str(2)
memory usage: 258.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   truck_id            3312 non-null   str
 1   month               3312 non-null   datetime64[us]
 2   trips_completed     3312 non-null   int64
 3   total_miles         3312 non-null   int64
 4   total_revenue       3312 non-null   float64
 5   average_mpg         3312 non-null   float64
 6   maintenance_events  3312 non-null   int64
 7   maintenance_cost    3312 non-null   float64
 8   downtime_hours      3312 non-null   float64
 9   utilization_rate    3312 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(3), str(1)
memory usage: 258.9 KB

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,2022-01-01,22,39269,84792.02,6.78,2,4380.98,63.1,0.710
1,TRK00001,2022-02-01,27,40787,88809.05,6.23,0,0.00,0.0,0.964
2,TRK00001,2022-03-01,34,57422,120453.71,6.49,0,0.00,0.0,1.097
3,TRK00001,2022-04-01,20,34428,73531.28,6.50,2,3548.15,71.8,0.667
4,TRK00001,2022-05-01,16,20851,40791.53,6.38,1,1969.42,43.9,0.516

In [121]:
# Importing & Cleaning trucks Table

trucks_df=pd.read_csv('trucks.csv')
trucks_df.info()
trucks_df['acquisition_date']=pd.to_datetime(trucks_df['acquisition_date'])
trucks_df['home_terminal'] = trucks_df['home_terminal'].str.title()
trucks_df.columns = trucks_df.columns.str.strip()
trucks_df.info()
trucks_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    str
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    str
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    str
 5   acquisition_date       120 non-null    str
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    str
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    str
 10  home_terminal          120 non-null    str
dtypes: int64(4), str(7)
memory usage: 10.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    str
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    str
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    str
 5   acquisition_date       120 non-null    datetime64[us]
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    str
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    str
 10  home_terminal          120 non-null    str
dtypes: datetime64[us](1), int64(4), str(6)
memory usage: 10.4 KB

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150,Maintenance,Atlanta
3,TRK00004,3317,Freightliner,2015,1VV131945381692351,2017-06-17,8875,Diesel,200,Active,Salt Lake City
4,TRK00005,6731,Freightliner,2016,1FT822215709701985,2021-10-08,42042,Diesel,250,Maintenance,Miami

In [122]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables

## 1- drop from loads table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(loads_df)

condition = False

if 'driver_id' in loads_df.columns:
    condition = loads_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in loads_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | loads_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in loads_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | loads_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    loads_df = loads_df[condition]
    deleted = initial_count - len(loads_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

loads_df.info()

❌ مفيش أي أعمدة مطابقة للفلترة
<class 'pandas.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  str
 1   customer_id          85410 non-null  str
 2   route_id             85410 non-null  str
 3   load_date            85410 non-null  datetime64[us]
 4   load_type            85410 non-null  str
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  str
 11  booking_type         85410 non-null  str
dtypes: datetime64[us](1), float64(2), int64(3), str(6)
memory usage: 7.8 MB

In [123]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 2- drop from customers table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(customers_df)

condition = False

if 'driver_id' in customers_df.columns:
    condition = customers_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in customers_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition |customers_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in customers_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | customers_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    customers_df = customers_df[condition]
    deleted = initial_count - len(customers_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

customers_df.info()

❌ مفيش أي أعمدة مطابقة للفلترة
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    str
 1   customer_name             200 non-null    str
 2   customer_type             200 non-null    str
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    str
 5   account_status            200 non-null    str
 6   contract_start_date       200 non-null    datetime64[us]
 7   annual_revenue_potential  200 non-null    int64
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 12.6 KB

In [124]:

# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 3- drop from drivers table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(drivers_df)

condition = False

if 'driver_id' in drivers_df.columns:
    condition = drivers_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in drivers_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | drivers_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in drivers_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | drivers_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    drivers_df = drivers_df[condition]
    deleted = initial_count - len(drivers_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

drivers_df.info()

✅ تم التنظيف | حذف: 26 صفوف
<class 'pandas.DataFrame'>
Index: 124 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          124 non-null    str
 1   first_name         124 non-null    str
 2   last_name          124 non-null    str
 3   hire_date          124 non-null    str
 4   termination_date   124 non-null    object
 5   license_number     124 non-null    str
 6   license_state      124 non-null    str
 7   date_of_birth      124 non-null    str
 8   home_terminal      124 non-null    str
 9   employment_status  124 non-null    str
 10  cdl_class          124 non-null    str
 11  years_experience   124 non-null    int64
dtypes: int64(1), object(1), str(10)
memory usage: 12.6+ KB

In [125]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 4-drop from delivery_events table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(delivery_events_df)

condition = False

if 'driver_id' in delivery_events_df.columns:
    condition = delivery_events_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in delivery_events_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | delivery_events_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in delivery_events_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | delivery_events_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    delivery_events_df = delivery_events_df[condition]
    deleted = initial_count - len(delivery_events_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

delivery_events_df.info()

❌ مفيش أي أعمدة مطابقة للفلترة
<class 'pandas.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  str
 1   load_id             170820 non-null  str
 2   trip_id             170820 non-null  str
 3   event_type          170820 non-null  str
 4   facility_id         170820 non-null  str
 5   scheduled_datetime  170820 non-null  datetime64[us]
 6   actual_datetime     170820 non-null  datetime64[us]
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  str
 10  location_state      170820 non-null  str
dtypes: bool(1), datetime64[us](2), int64(1), str(7)
memory usage: 13.2 MB

In [126]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 5-drop from driver_monthly_metrics table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(driver_monthly_metrics_df)

condition = False

if 'driver_id' in driver_monthly_metrics_df.columns:
    condition = driver_monthly_metrics_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in driver_monthly_metrics_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | driver_monthly_metrics_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in driver_monthly_metrics_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | driver_monthly_metrics_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    driver_monthly_metrics_df = driver_monthly_metrics_df[condition]
    deleted = initial_count - len(driver_monthly_metrics_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

driver_monthly_metrics_df.info()

✅ تم التنظيف | حذف: 0 صفوف
<class 'pandas.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4464 non-null   str
 1   month                  4464 non-null   datetime64[us]
 2   trips_completed        4464 non-null   int64
 3   total_miles            4464 non-null   int64
 4   total_revenue          4464 non-null   float64
 5   average_mpg            4464 non-null   float64
 6   total_fuel_gallons     4464 non-null   float64
 7   on_time_delivery_rate  4464 non-null   float64
 8   average_idle_hours     4464 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(2), str(1)
memory usage: 314.0 KB

In [127]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 6-drop from facilities table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(facilities_df)

condition = False

if 'driver_id' in facilities_df.columns:
    condition = facilities_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in facilities_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | facilities_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in facilities_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | facilities_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    facilities_df = facilities_df[condition]
    deleted = initial_count - len(facilities_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

facilities_df.info()

❌ مفيش أي أعمدة مطابقة للفلترة
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   facility_id      50 non-null     str
 1   facility_name    50 non-null     str
 2   facility_type    50 non-null     str
 3   city             50 non-null     str
 4   state            50 non-null     str
 5   latitude         50 non-null     float64
 6   longitude        50 non-null     float64
 7   dock_doors       50 non-null     int64
 8   operating_hours  50 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 3.6 KB

In [128]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
##7- drop from fuel_purchases table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(fuel_purchases_df)

condition = False

if 'driver_id' in fuel_purchases_df.columns:
    condition = fuel_purchases_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in fuel_purchases_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | fuel_purchases_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in fuel_purchases_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | fuel_purchases_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    fuel_purchases_df = fuel_purchases_df[condition]
    deleted = initial_count - len(fuel_purchases_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

fuel_purchases_df.info()

✅ تم التنظيف | حذف: 0 صفوف
<class 'pandas.DataFrame'>
Index: 188668 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  188668 non-null  str
 1   trip_id           188668 non-null  str
 2   truck_id          188668 non-null  str
 3   driver_id         188668 non-null  str
 4   purchase_date     188668 non-null  datetime64[us]
 5   location_city     188668 non-null  str
 6   location_state    188668 non-null  str
 7   gallons           188668 non-null  float64
 8   price_per_gallon  188668 non-null  float64
 9   total_cost        188668 non-null  float64
 10  fuel_card_number  188668 non-null  str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 17.3 MB

In [129]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 8-drop from maintenance_records table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(maintenance_records_df)

condition = False

if 'driver_id' in maintenance_records_df.columns:
    condition = maintenance_records_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in maintenance_records_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | maintenance_records_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in maintenance_records_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | maintenance_records_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    maintenance_records_df = maintenance_records_df[condition]
    deleted = initial_count - len(maintenance_records_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

maintenance_records_df.info()

✅ تم التنظيف | حذف: 690 صفوف
<class 'pandas.DataFrame'>
Index: 2230 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2230 non-null   str
 1   truck_id             2230 non-null   str
 2   maintenance_date     2230 non-null   datetime64[us]
 3   maintenance_type     2230 non-null   str
 4   odometer_reading     2230 non-null   int64
 5   labor_hours          2230 non-null   float64
 6   labor_cost           2230 non-null   float64
 7   parts_cost           2230 non-null   float64
 8   total_cost           2230 non-null   float64
 9   facility_location    2230 non-null   str
 10  downtime_hours       2230 non-null   float64
 11  service_description  2230 non-null   str
dtypes: datetime64[us](1), float64(5), int64(1), str(5)
memory usage: 226.5 KB

In [130]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 9-drop from routes table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(routes_df)

condition = False

if 'driver_id' in routes_df.columns:
    condition = routes_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in routes_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | routes_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in routes_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | routes_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    routes_df = routes_df[condition]
    deleted = initial_count - len(routes_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

routes_df.info()

❌ مفيش أي أعمدة مطابقة للفلترة
<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     str
 1   origin_city             58 non-null     str
 2   origin_state            58 non-null     str
 3   destination_city        58 non-null     str
 4   destination_state       58 non-null     str
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), str(5)
memory usage: 4.2 KB

In [131]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 10-drop from safety_incidents table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(safety_incidents_df)

condition = False

if 'driver_id' in safety_incidents_df.columns:
    condition = safety_incidents_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in safety_incidents_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | safety_incidents_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in safety_incidents_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition |safety_incidents_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    safety_incidents_df = safety_incidents_df[condition]
    deleted = initial_count - len(safety_incidents_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

safety_incidents_df.info()

✅ تم التنظيف | حذف: 0 صفوف
<class 'pandas.DataFrame'>
Index: 168 entries, 0 to 169
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   incident_id          168 non-null    str
 1   trip_id              168 non-null    str
 2   truck_id             168 non-null    str
 3   driver_id            168 non-null    str
 4   incident_date        168 non-null    datetime64[us]
 5   incident_type        168 non-null    str
 6   location_city        168 non-null    str
 7   location_state       168 non-null    str
 8   at_fault_flag        168 non-null    bool
 9   injury_flag          168 non-null    bool
 10  vehicle_damage_cost  168 non-null    float64
 11  cargo_damage_cost    168 non-null    float64
 12  claim_amount         168 non-null    float64
 13  preventable_flag     168 non-null    bool
 14  description          168 non-null    str
dtypes: bool(3), datetime64[us](1), float64(3), str(8)
memory usage: 17.6 KB

In [132]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 11-drop from trailers table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(trailers_df)

condition = False

if 'driver_id' in trailers_df.columns:
    condition = trailers_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in trailers_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | trailers_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in trailers_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | trailers_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    trailers_df = trailers_df[condition]
    deleted = initial_count - len(trailers_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

trailers_df.info()

✅ تم التنظيف | حذف: 0 صفوف
<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trailer_id        180 non-null    str
 1   trailer_number    180 non-null    int64
 2   trailer_type      180 non-null    str
 3   length_feet       180 non-null    int64
 4   model_year        180 non-null    int64
 5   vin               180 non-null    str
 6   acquisition_date  180 non-null    datetime64[us]
 7   status            180 non-null    str
 8   current_location  180 non-null    str
dtypes: datetime64[us](1), int64(3), str(5)
memory usage: 12.8 KB

In [133]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
## 12-drop from truck_utilization_metrics table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(truck_utilization_metrics_df)

condition = False

if 'driver_id' in truck_utilization_metrics_df.columns:
    condition = truck_utilization_metrics_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in truck_utilization_metrics_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | truck_utilization_metrics_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in truck_utilization_metrics_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | truck_utilization_metrics_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    truck_utilization_metrics_df = truck_utilization_metrics_df[condition]
    deleted = initial_count - len(truck_utilization_metrics_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

truck_utilization_metrics_df.info()

✅ تم التنظيف | حذف: 0 صفوف
<class 'pandas.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   truck_id            3312 non-null   str
 1   month               3312 non-null   datetime64[us]
 2   trips_completed     3312 non-null   int64
 3   total_miles         3312 non-null   int64
 4   total_revenue       3312 non-null   float64
 5   average_mpg         3312 non-null   float64
 6   maintenance_events  3312 non-null   int64
 7   maintenance_cost    3312 non-null   float64
 8   downtime_hours      3312 non-null   float64
 9   utilization_rate    3312 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(3), str(1)
memory usage: 258.9 KB

In [134]:
# drop driver_id , truck_id & trailer_id that has no data in trips table from other tables
##13- drop from trucks table

valid_driver_ids = set(trips_df['driver_id'].dropna())

initial_count = len(trucks_df)

condition = False

if 'driver_id' in trucks_df.columns:
    condition = trucks_df['driver_id'].isin(valid_driver_ids)

if 'truck_id' in trucks_df.columns:
    valid_truck_ids = set(trips_df['truck_id'].dropna())
    condition = condition | trucks_df['truck_id'].isin(valid_truck_ids)

if 'trailer_id' in trucks_df.columns:
    valid_trailer_ids = set(trips_df['trailer_id'].dropna())
    condition = condition | trucks_df['trailer_id'].isin(valid_trailer_ids)

# تطبيق الفلترة لو في أي شرط
if isinstance(condition, bool):
    print("❌ مفيش أي أعمدة مطابقة للفلترة")
else:
    trucks_df = trucks_df[condition]
    deleted = initial_count - len(trucks_df)
    print(f"✅ تم التنظيف | حذف: {deleted} صفوف")

trucks_df.info()

✅ تم التنظيف | حذف: 28 صفوف
<class 'pandas.DataFrame'>
Index: 92 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               92 non-null     str
 1   unit_number            92 non-null     int64
 2   make                   92 non-null     str
 3   model_year             92 non-null     int64
 4   vin                    92 non-null     str
 5   acquisition_date       92 non-null     datetime64[us]
 6   acquisition_mileage    92 non-null     int64
 7   fuel_type              92 non-null     str
 8   tank_capacity_gallons  92 non-null     int64
 9   status                 92 non-null     str
 10  home_terminal          92 non-null     str
dtypes: datetime64[us](1), int64(4), str(6)
memory usage: 8.6 KB

In [135]:
# Saving clean files

loads_df.to_csv('loads_c.csv')
customers_df.to_csv('customers_c.csv')
drivers_df.to_csv('drivers_c.csv')
delivery_events_df.to_csv('delivery_events_c.csv')
driver_monthly_metrics_df.to_csv('driver_monthly_metrics_c.csv')
facilities_df.to_csv('facilities_c.csv')
fuel_purchases_df.to_csv('fuel_purchases_c.csv')
maintenance_records_df.to_csv('maintenance_records_c.csv')
routes_df.to_csv('routes_c.csv')
safety_incidents_df.to_csv('safety_incidents_c.csv')
trailers_df.to_csv('trailers_c.csv')
trips_df.to_csv('trips_df_c.csv')
truck_utilization_metrics_df.to_csv('truck_utilization_metrics_c.csv')
trucks_df.to_csv('trucks_c.csv')